---
name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "bin/**"
      - "examples/**"
      - "*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "bin/**"
      - "examples/**"
      - "*.md"
jobs:
  tests:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - 2.1
          - 2.2
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 3.0
          - ruby-head
          - jruby-9.2.13.0
          - jruby-head
          - truffleruby-head
        include:
          - ruby: 2.7
            os: ubuntu-latest
            coverage: true
    env:
      COVERAGE: ${{ matrix.coverage }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      BUNDLE_CACHE_PATH: vendor/bundle
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler -v '< 2.0'
      - name: Cache dependencies
        id: cache-gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ matrix.ruby }}-gems-${{ hashFiles('*.gemspec') }}-${{ hashFiles('Gemfile') }}
      - name: Install dependencies
        if: steps.cache-gems.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Update dependencies
        if: steps.cache-gems.outputs.cache-hit == 'true'
        run: bundle update
      - name: Run tests
        run: bundle exec rake ci
